version: "3.9"

services:
  api:
    build: .
    container_name: clv_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MODEL_PATH=models/clv_best_model.pkl
      - REFERENCE_DATA_PATH=cleaned_data/customer_data_rfm.csv
      - PYTHONPATH=/app
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: clv_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
